<?php

/**
 * @file
 * Defines the exports.
 */

use GuzzleHttp\Client as HttpClient;


/**
 * Implements hook_menu().
 */
function aakb_edb_menu() {
  $items = array();

  $items['feeds/eventdb'] = array(
    'title' => 'Events',
    'type' => MENU_CALLBACK,
    'page callback' => 'aakb_edb_feed',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Build JSON feed with current events.
 */
function aakb_edb_feed() {
  module_load_include('inc', 'ding_pretix', 'ding_pretix.api_module');

  $events = array();

  $cache = cache_get('aakb_edb_events', 'cache');
  if ($cache && time() < $cache->expire) {
    $events = $cache->data;
  }
  else {
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'ding_event')
      ->propertyCondition('status', NODE_PUBLISHED)
      ->fieldCondition('field_ding_event_date', 'value', strtotime("midnight", time()), '>=');

    $result = $query->execute();
    if (isset($result['node'])) {
      $nids = array_keys($result['node']);
      $nodes = entity_load('node', $nids);

      foreach ($nodes as $node) {
        $wrapper = entity_metadata_wrapper('node', $node);

        $tags = array();
        $tagObjects = $wrapper->field_ding_event_tags->value();
        foreach ($tagObjects as $tag) {
          $tags[] = $tag->name;
        }

        $category = $wrapper->field_ding_event_category->value()->name;

        // For the DOKK1 integration we need the category. But the EventDB
        // has no "category" feature. This extre field allows the EventDB
        // to include the category as a tag
        $category_tags = array_unique(array_merge([$category], $tags));

        $groups = [];
        $groupObjects = $wrapper->ding_event_groups_ref->value();
        foreach ($groupObjects as $group) {
          $groups[] = array(
            'nid' => $group->nid,
            'title' => $group->title,
            'link' => url('node/' . $group->nid, array(
              'absolute' => TRUE,
            )),
          );
        }

        $timezone = $wrapper->field_ding_event_date->value()['timezone_db'];
        $dt = new DateTime($wrapper->field_ding_event_date->value()['value'], new DateTimeZone($timezone));
        $start = $dt->format('c');
        $dt = new DateTime($wrapper->field_ding_event_date->value()['value2'], new DateTimeZone($timezone));
        $stop = $dt->format('c');

        $og_group = $wrapper->og_group_ref->value();
        $og_group = $og_group ? reset($og_group) : $og_group;

        try {
          $group_wrapper = entity_metadata_wrapper('node', $og_group);
        }
        catch (EntityMetadataWrapperException $e) {
          // Not connected to a library.
        }

        try {
          $address = $group_wrapper->field_ding_library_addresse->value();
          $location = array(
            'hint' => $wrapper->field_ding_event_location->value()['name_line'],
            'thoroughfare' => $address['thoroughfare'],
            'postal_code' => $address['postal_code'],
            'locality' => $address['locality'],
            'mail' => $group_wrapper->field_ding_library_mail->value(),
            'phone' => $group_wrapper->field_ding_library_phone_number->value(),
            'name' => $group_wrapper->title->value(),
          );
        }
        catch (EntityMetadataWrapperException $e) {
          $location = array();
        }

        try {
          $geo = $group_wrapper->field_ding_library_geocode->value();
          $location['coordinates'] = array(
            'lat' => $geo['lat'],
            'lon' => $geo['lon'],
          );
        }
        catch (EntityMetadataWrapperException $e) {
          // Don't do anything.
        }

        $tickets = array();
        $external_ticket = $wrapper->field_ding_event_ticket_link->value();
        if (isset($external_ticket)) {
          $tickets['url'] = $external_ticket['url'];
        }

        $lead_wrapper = $wrapper->field_ding_event_lead->value();
        $body_wrapper = $wrapper->field_ding_event_body->value();

        $lead = $lead_wrapper['safe_value'] ?? $lead_wrapper;
        $body = $body_wrapper['safe_value'] ?? '';

        // 'Det Sker i Aarhus' data model has no 'lead' concept so we have to merge 'lead' and 'body'.
        $description = $lead ? '<p><strong>'. $lead .'</strong></p> ' . $body : $body;

        $partners = [];
        try {
          $event_organizer_terms = $wrapper->field_ding_event_organizers->value();

          foreach ($event_organizer_terms as $event_organizer) {
            $partner = [];
            $partner['id'] = $event_organizer->tid;
            $partner['name'] = $event_organizer->name;
            // name="field_remote_id[und][0][value]"
            $partner['remote_id'] = !empty($event_organizer->field_remote_id) ? $event_organizer->field_remote_id[LANGUAGE_NONE][0]['value'] : '';
            // name="field_event_organizer_link[und][0][url]"
            $partner['url'] = !empty($event_organizer->field_event_organizer_link) ? $event_organizer->field_event_organizer_link[LANGUAGE_NONE][0]['url'] : '';

            $partners[] = $partner;
          }
        }
        catch (EntityMetadataWrapperException $e) {
          // Don't do anything.
        }

        $events[] = array(
          'nid' => $node->nid,
          'url' => url('node/' . $node->nid, array(
            'absolute' => TRUE,
          )),
          'title' => $node->title,
          'language' => $node->language,
          'changed' => date('c', $node->changed),
          'category' => $category,
          'tags' => $tags,
          'category_tags' => $category_tags,
          'groups' => $groups,
          'lead' => $lead,
          'body' => $description,
          'date' => array(
            'start' => $start,
            'stop' => $stop,
          ),
          'images' => array(
            'list' => $wrapper->field_ding_event_list_image->value() ? file_create_url($wrapper->field_ding_event_list_image->value()['uri']) : '',
            'title' => $wrapper->field_ding_event_title_image->value() ? file_create_url($wrapper->field_ding_event_title_image->value()['uri']) : '',
          ),
          'location' => $location,
          'room' => $wrapper->field_ding_event_place->value() ?? '',
          'price' => $wrapper->field_ding_event_price->value() ?? 0,
          'targets' => $wrapper->field_ding_event_target->value() ?? '',
          'unpublish_on' => isset($node->unpublish_on) ? date('c', $node->unpublish_on) : 0,
          'partners' => $partners,
          'tickets' => $tickets,
        );
      }
    }

    // Store the result in cache for an hour.
    cache_set('aakb_edb_events', $events, 'cache', REQUEST_TIME + 3600);
  }

  drupal_json_output($events);
}

/**
 * Implements hook_cron().
 */
function aakb_edb_cron() {
  aakb_edb_sync_organizer();
}

/**
 * Updates taxonomy on ding_event with organizer from detskeriaarhus.dk.
 */
function aakb_edb_sync_organizer() {
  $results = _aakb_edb_get_organizers();

  $vocabulary = taxonomy_vocabulary_machine_name_load('event_organizer');
  $vid = $vocabulary->vid;

  $new_term = (object) array(
    'name' => '',
    'description' => '',
    'vid' => $vid,
    'field_event_organizer_link' => array(
      LANGUAGE_NONE => array(
        array(
          'url' => '',
          'title' => NULL,
          'attributes' => array(),
        ),
      ),
    ),
    'field_remote_id' => array(
      LANGUAGE_NONE => array(
        array(
          'value' => '',
        ),
      ),
    ),
  );

  foreach ($results as $result) {
    $efq = new EntityFieldQuery();
    $existing = $efq->entityCondition('entity_type', 'taxonomy_term')
      ->propertyCondition('vid', $vid)
      ->fieldCondition('field_remote_id', 'value', $result->id)
      ->execute();

    if (empty($existing)) {
      $term = clone $new_term;
    }
    else {
      $tids = array_keys($existing['taxonomy_term']);
      $term = taxonomy_term_load(reset($tids));
    }

    $term->name = $result->name;
    $term->field_event_organizer_link[LANGUAGE_NONE][0]['url'] = $result->url;
    $term->field_remote_id[LANGUAGE_NONE][0]['value'] = $result->id;
    taxonomy_term_save($term);
  }
}

/**
 * Link existing organizers by name.
 */
function aakb_edb_link_organizers() {
  $results = _aakb_edb_get_organizers();

  $vocabulary = taxonomy_vocabulary_machine_name_load('event_organizer');
  $vid = $vocabulary->vid;

  foreach ($results as $result) {
    $efq = new EntityFieldQuery();
    $existing = $efq->entityCondition('entity_type', 'taxonomy_term')
      ->propertyCondition('vid', $vid)
      ->propertyCondition('name', $result->name)
      ->execute();

    if (empty($existing)) {
      drush_print(dt('Cannot find term with name @name', array('@name' => $result->name)));
      continue;
    }
    else {
      $tids = array_keys($existing['taxonomy_term']);
      $term = taxonomy_term_load(reset($tids));
      if (isset($term->field_remote_id[LANGUAGE_NONE][0]['value'])) {
        drush_print(dt('Term @name already linked (remote id: @remote_id)',
          array('@name' => $result->name, '@remote_id' => $result->id)));
        continue;
      } else {
        drush_print(dt('Linking term @name (remote id: @remote_id)',
          array('@name' => $result->name, '@remote_id' => $result->id)));
      }
    }

    $term->name = $result->name;
    $term->field_event_organizer_link[LANGUAGE_NONE][0]['url'] = $result->url;
    $term->field_remote_id[LANGUAGE_NONE][0]['value'] = $result->id;
    taxonomy_term_save($term);
  }
}

/**
 * List organizers without remote id.
 */
function aakb_edb_list_orphaned_event_organizers() {
  $vocabulary = taxonomy_vocabulary_machine_name_load('event_organizer');
  $vid = $vocabulary->vid;

  $efq = new EntityFieldQuery();
  $result = $efq->entityCondition('entity_type', 'taxonomy_term')
    ->propertyCondition('vid', $vid)
    ->execute();

  if (isset($result['taxonomy_term'])) {
    $terms = taxonomy_term_load_multiple(array_keys($result['taxonomy_term']));
    foreach ($terms as $term) {
      if (!isset($term->field_remote_id[LANGUAGE_NONE][0]['value'])) {
        drush_print(dt('Term @name (#@id) does not have a remote id',
          array('@name' => $term->name, '@id' => $term->tid)));
      }
    }
  }
}

/**
 * Get all organizer from Event Database.
 *
 * @return array|stdClass[]
 *   The list of organizers.
 */
function _aakb_edb_get_organizers() {
  $endpoint_base_url = 'https://api.detskeriaarhus.dk';
  $endpoint = $endpoint_base_url.'/api/organizers';

  $results = [];
  while (NULL !== $endpoint) {
    $client = new HttpClient();
    $response = $client->get(
      $endpoint,
      array(
        'headers' => array(
          'accept' => 'application/ld+json',
        ),
      )
    );
    $data = json_decode($response->getBody());

    $endpoint = isset($data->{'hydra:view'}->{'hydra:next'}) ? $endpoint_base_url.$data->{'hydra:view'}->{'hydra:next'} : NULL;

    if (isset($data->{'hydra:member'})) {
      $results[] = $data->{'hydra:member'};
    }
  }

  // Flatten result.
  return array_merge(...$results);
}
